### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GHeeJeon** [GHeeJeon/GHeeJeon.github.io#3]
- [x] 테마 ~컬러~ 갈아엎기
- [x] 한글 폰트 추가하기
- [x] 카테고리 별로 구분 할 수 있게끔 만들기
- [x] 클릭 할 때마다 장미 도장 찍기
- [x] ~css도 손봐주세요 너무 구려요~ 아예 테마를 갈아엎는 게 낫지 않을까요...?
-  [x] 샘플로 채워져 있는 내용 갈아엎기
-  [x] 샘플 이미지 변경하기
-  [x] 기존 포스트 정리하기

**Comment by GHeeJeon** [comment]
결국 웹스톰을 켜야 하나... 어차피 마크다운인데 걍 깃헙에서 할까...

**Comment by GHeeJeon** [comment]
초록초록한 컬러도 갈아엎자.
`#CCCCFF`
`#FF91A4`

`#fa8072`

**Comment by GHeeJeon** [comment]
테마 후보
http://bogoli.github.io/-folio/ 당첨!
https://blog.base68.com/

**Comment by GHeeJeon** [comment]
> 카테고리 별로 구분 할 수 있게끔 만들기

테마 바꾸니까 해-결^^
